apiVersion: batch/v1
kind: CronJob
metadata:
  name: hmpps-micro-frontend-components-services
spec:
  schedule: "{{ .Values.services_cronjob_schedule }}"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hmpps-micro-frontend-components-services-cronjob
              image: quay.io/hmpps/hmpps-micro-frontend-components
              args:
                - npm run getAppsStatus
          restartPolicy: Never