apiVersion: batch/v1
kind: CronJob
metadata:
  name: hmpps-micro-frontend-components-services
spec:
  schedule: "{{ .Values.services_cronjob_schedule }}"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hmpps-micro-frontend-components-services-cronjob
              image: "{{ index .Values "generic-service" "image" "repository" }}:{{ index .Values "generic-service" "image" "tag" | default .Chart.AppVersion }}"
              env:
              - name: ENVIRONMENT
                value: "{{ index .Values "generic-service" "env" "ENVIRONMENT" }}"
              - name: ENVIRONMENT_NAME
                value: "{{ index .Values "generic-service" "env" "ENVIRONMENT_NAME" }}"
              - name: ACTIVITIES_URL
                value: "{{ index .Values "generic-service" "env" "ACTIVITIES_URL" }}"
              - name: CAS2_URL
                value: "{{ index .Values "generic-service" "env" "CAS2_URL" }}"
              - name: CAS2_BAIL_URL
                value: "{{ index .Values "generic-service" "env" "CAS2_BAIL_URL" }}"
              - name: ALERTS_API_URL
                value: "{{ index .Values "generic-service" "env" "ALERTS_API_URL" }}"
              - name: REPORTING_URL
                value: "{{ index .Values "generic-service" "env" "REPORTING_URL" }}"
              - name: RESIDENTIAL_LOCATIONS_API_URL
                value: "{{ index .Values "generic-service" "env" "RESIDENTIAL_LOCATIONS_API_URL" }}"
              - name: LEARNING_AND_WORK_PROGRESS_URL
                value: "{{ index .Values "generic-service" "env" "LEARNING_AND_WORK_PROGRESS_URL" }}"
              - name: WHEREABOUTS_API_URL
                value: "{{ index .Values "generic-service" "env" "WHEREABOUTS_API_URL" }}"
              - name: CSIP_API_URL
                value: "{{ index .Values "generic-service" "env" "CSIP_API_URL" }}"
              - name: INCIDENT_REPORTING_URL
                value: "{{ index .Values "generic-service" "env" "INCIDENT_REPORTING_URL" }}"
              - name: CASE_NOTES_API_URL
                value: "{{ index .Values "generic-service" "env" "CASE_NOTES_API_URL" }}"
              - name: PREPARE_SOMEONE_FOR_RELEASE_URL
                value: "{{ index .Values "generic-service" "env" "PREPARE_SOMEONE_FOR_RELEASE_URL" }}"
              - name: CEMO_URL
                value: "{{ index .Values "generic-service" "env" "CEMO_URL" }}"
              - name: MANAGE_APPLICATIONS_URL
                value: "{{ index .Values "generic-service" "env" "MANAGE_APPLICATIONS_URL" }}"
              - name: ALLOCATE_KEY_WORKERS_API_URL
                value: "{{ index .Values "generic-service" "env" "ALLOCATE_KEY_WORKERS_API_URL" }}"
              - name: EXTERNAL_MOVEMENTS_API_URL
                value: "{{ index .Values "generic-service" "env" "EXTERNAL_MOVEMENTS_API_URL" }}"
              - name: ALLOCATE_PERSONAL_OFFICERS_API_URL
                value: "{{ index .Values "generic-service" "env" "ALLOCATE_PERSONAL_OFFICERS_API_URL" }}"
              - name: SUPPORT_ADDITIONAL_NEEDS_URL
                value: "{{ index .Values "generic-service" "env" "SUPPORT_ADDITIONAL_NEEDS_URL" }}"
              - name: REDIS_HOST
                valueFrom:
                  secretKeyRef:
                    name: elasticache-redis
                    key: primary_endpoint_address
              - name: REDIS_AUTH_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: elasticache-redis
                    key: auth_token
              - name: REDIS_TLS_ENABLED
                value: "{{ index .Values "generic-service" "env" "REDIS_TLS_ENABLED" }}"
              command: ["npm", "run", "getAppsStatus", "--loglevel", "verbose"]
          restartPolicy: Never
          activeDeadlineSeconds: 300
