---
generic-service:
  nameOverride: hmpps-micro-frontend-components
  productId: DPS019

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-micro-frontend-components
    tag: app_version    # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-micro-frontend-components-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_ENABLED: "true"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    MATCH_LEARNER_RECORD_ENABLED: "true"
    SUPPORT_ADDITIONAL_NEEDS_ENABLED: "true"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-micro-frontend-components:
      CONTENTFUL_SPACE_ID: "CONTENTFUL_SPACE_ID"
      CONTENTFUL_ACCESS_TOKEN: "CONTENTFUL_ACCESS_TOKEN"
    hmpps-micro-frontend-components-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-micro-frontend-components-auth-code:
      API_CLIENT_ID: "AUTH_CODE_CLIENT_ID"
      API_CLIENT_SECRET: "AUTH_CODE_CLIENT_SECRET"
    hmpps-micro-frontend-components-client-creds:
      SYSTEM_CLIENT_ID: "CLIENT_CREDS_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "CLIENT_CREDS_CLIENT_SECRET"
    hmpps-micro-frontend-components-session-secret:
      SESSION_SECRET: "SESSION_SECRET"
    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"

generic-prometheus-alerts:
  targetApplication: hmpps-micro-frontend-components
