import express from 'express'
import swaggerUi from 'swagger-ui-express'
// @ts-expect-error openApiSpec file is generated by esbuild
// eslint-disable-next-line import/extensions
import openApiSpec from '../routes/openApiSpec'

export default function setUpSwagger(app: express.Express) {
  app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(openApiSpec))
}
