services_cronjob_schedule: "0 * * * *"

generic-service:
  replicaCount: 4

  ingress:
    host: frontend-components.hmpps.service.justice.gov.uk

  autoscaling:
    enabled: true
    minReplicas: 8
    maxReplicas: 16
    targetCPUUtilizationPercentage: 1600

  env:
    INGRESS_URL: "https://frontend-components.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    SUPPORT_URL: "https://support.hmpps.service.justice.gov.uk/feedback-and-support"
    PRISON_API_URL: "https://prison-api.prison.service.justice.gov.uk"
    CONTENTFUL_HOST: "https://graphql.eu.contentful.com"
    CONTENTFUL_ENVIRONMENT: master
    CONTENTFUL_FOOTER_LINKS_ENABLED: false
    ENVIRONMENT_NAME: PRODUCTION
    CACHE_TIMOUT: 600

    DPS_URL: https://digital.prison.service.justice.gov.uk
    NEW_DPS_URL: https://dps.prison.service.justice.gov.uk
    OMIC_URL: https://manage-key-workers.service.justice.gov.uk
    ACTIVITIES_URL: https://activities.prison.service.justice.gov.uk
    APPOINTMENTS_URL: https://activities.prison.service.justice.gov.uk
    CHECK_MY_DIARY_URL: https://checkmydiary.service.justice.gov.uk?fromDPS=true
    INCENTIVES_URL: https://incentives-ui.hmpps.service.justice.gov.uk
    USE_OF_FORCE_URL: https://use-of-force.service.justice.gov.uk
    PATHFINDER_URL: https://pathfinder.service.justice.gov.uk
    LICENCES_URL: https://licences.prison.service.justice.gov.uk
    MOIC_URL: https://moic.service.justice.gov.uk
    MANAGE_AUTH_ACCOUNTS_URL: https://manage-users.hmpps.service.justice.gov.uk
    CATEGORISATION_URL: https://offender-categorisation.service.justice.gov.uk
    PECS_URL: https://bookasecuremove.service.justice.gov.uk
    SOC_URL: https://manage-soc-cases.hmpps.service.justice.gov.uk
    PIN_PHONES_URL: https://pcms.prison.service.justice.gov.uk
    MANAGE_ADJUDICATIONS_URL: https://manage-adjudications.hmpps.service.justice.gov.uk
    MANAGE_PRISON_VISITS_URL: https://manage-prison-visits.prison.service.justice.gov.uk
    LEGACY_PRISON_VISITS_URL: https://staff.prisonvisits.service.justice.gov.uk
    SECURE_SOCIAL_VIDEO_CALLS_URL: https://auth.phonehub.io/accounts/login/oauth/redirect
    SEND_LEGAL_MAIL_URL: https://check-rule39-mail.prison.service.justice.gov.uk
    WELCOME_PEOPLE_INTO_PRISON_URL: https://welcome.prison.service.justice.gov.uk
    MERCURY_SUBMIT_URL: https://submit-a-mercury-report.hmpps.service.justice.gov.uk
    MANAGE_INTELLIGENCE_URL: https://manage-intelligence.prison.service.justice.gov.uk
    MANAGE_RESTRICTED_PATIENTS_URL: https://manage-restricted-patients.hmpps.service.justice.gov.uk
    CREATE_AND_VARY_A_LICENCE_URL: https://create-and-vary-a-licence.hmpps.service.justice.gov.uk
    HISTORICAL_PRISONER_APPLICATION_URL: https://historical-prisoner.prison.service.justice.gov.uk
    WORK_AFTER_LEAVING_PRISON_URL: https://get-ready-for-work.hmpps.service.justice.gov.uk
    MANAGE_OFFENCES_URL: https://manage-offences.hmpps.service.justice.gov.uk
    LEARNING_AND_WORK_PROGRESS_URL: https://learning-and-work-progress.hmpps.service.justice.gov.uk
    PREPARE_SOMEONE_FOR_RELEASE_URL: https://resettlement-passport-ui.hmpps.service.justice.gov.uk
    CAS2_URL: https://short-term-accommodation-cas-2.hmpps.service.justice.gov.uk
    CHANGE_SOMEONES_CELL_URL: https://change-someones-cell.prison.service.justice.gov.uk
    ACCREDITED_PROGRAMMES_URL: https://accredited-programmes.hmpps.service.justice.gov.uk
    ALERTS_API_URL: https://alerts-api.hmpps.service.justice.gov.uk
    ALERTS_UI_URL: https://alerts-ui.hmpps.service.justice.gov.uk
    REPORTING_URL: https://digital-prison-reporting-mi-ui.hmpps.service.justice.gov.uk
    RESIDENTIAL_LOCATIONS_URL: https://locations-inside-prison.hmpps.service.justice.gov.uk
    RESIDENTIAL_LOCATIONS_API_URL: https://locations-inside-prison-api.hmpps.service.justice.gov.uk
    WHEREABOUTS_API_URL: https://whereabouts-api.service.justice.gov.uk
    CSIP_API_URL: https://csip-api.hmpps.service.justice.gov.uk
    CSIP_UI_URL: https://csip.hmpps.service.justice.gov.uk
    INCIDENT_REPORTING_URL: https://incident-reporting.hmpps.service.justice.gov.uk
    CASE_NOTES_API_URL: https://offender-case-notes.service.justice.gov.uk
    MANAGE_APPLICATIONS_URL: https://managing-prisoner-apps-staff-ui.hmpps.service.justice.gov.uk
    ESTABLISHMENT_ROLL_URL: https://prison-roll-count.hmpps.service.justice.gov.uk

    # Feature
    ACTIVITIES_ENABLED_PRISONS: "RSI,LPI"
    APPOINTMENTS_ENABLED_PRISONS: "RSI,LPI"
    USE_OF_FORCE_PRISONS: "ACI,AGI,ASI,AYI,BAI,BCI,BFI,BHI,BLI,BMI,BNI,BRI,BSI,BWI,BXI,BZI,CDI,CFI,CKI,CLI,CWI,DAI,DGI,DHI,DMI,DNI,DTI,DWI,EEI,EHI,ESI,EWI,EXI,EYI,FBI,FDI,FEI,FHI,FKI,FMI,FNI,FSI,FWI,GHI,GMI,GNI,GTI,HBI,HCI,HDI,HEI,HHI,HII,HLI,HMI,HOI,HPI,HVI,ISI,IWI,KMI,KVI,LCI,LEI,LFI,LGI,LHI,LII,LLI,LNI,LPI,LTI,LWI,LYI,MDI,MHI,MRI,MSI,MTI,NHI,NLI,NMI,NSI,NWI,ONI,OWI,PBI,PDI,PFI,PNI,PRI,PVI,RCI,RHI,RNI,RSI,SDI,SFI,SHI,SKI,SLI,SNI,SPI,STI,SUI,SWI,TCI,TSI,UKI,UPI,VEI,WCI,WDI,WEI,WHI,WII,WLI,WMI,WRI,WSI,WTI,WWI"
    MANAGE_ADJUDICATIONS_ENABLED: "RNI,WLI,MDI,EXI,BXI,PVI,NHI,DMI,BLI,LFI,NSI,SWI,BNI,STI,SPI,SUI,BSI,LWI,CFI,DTI,EEI,FSI,FNI,HMI,LHI,LLI,NMI,ONI,RCI,SKI,WNI,WCI,AGI,BWI,DWI,DHI,ESI,FMI,FHI,HDI,HOI,HHI,HLI,ISI,KVI,LEI,LNI,UPI,RSI,SDI,WWI,WII,WEI,WSI,FYI,UKI,WYI"
    WELCOME_PEOPLE_INTO_PRISON_ENABLED_PRISONS: "BFI,BNI,BWI,CDI,DMI,EXI,EYI,HEI,HLI,LCI,LEI,LII,LPI,LWI,MHI,NMI,NWI,PNI,PVI,WCI,WSI,WWI,STI"
    COVID_UNITS_ENABLED: false
    FEATURE_SERVICES_STORE_ENABLED: true
    ACCREDITED_PROGRAMMES_ENABLED: true
    REPORTING_ENABLED_PRISONS: "EXI,BNI,LYI,LYI"

  allowlist:
    sscl-blackpool: 31.121.5.27/32
    sscl-azure: 51.142.106.199/32
    sscl-york: 62.6.61.29/32
    sscl-newcastle: 62.172.79.105/32
    sscl-newport: 217.38.237.212/32
    groups:
      - internal
      - prisons
      - private_prisons
      - police

generic-prometheus-alerts:
  alertSeverity: hmpps-micro-frontend-components-prod

  elastiCacheAlertsClusterIds:
    cp-f4589ecbb0cf0715-001: "HMPPS Micro Frontend Components ElastiCache Cluster Node 1"
    cp-f4589ecbb0cf0715-002: "HMPPS Micro Frontend Components ElastiCache Cluster Node 2"
